### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by kabergstrom** [amethyst/atelier-assets#21]
The daemon panics on a lot of common user errors like file parsing errors right now. It should propagate asset import errors to the metadata state so that it can be shown to the user.

The loader should also handle errors better. There are scenarios where it panics, and others where errors lead to infinite retries.

**Comment by happenslol** [comment]
I'll try and take this on to get more familiar with the project. Will report back here if I have any questions =)

**Comment by happenslol** [comment]
I've opened up a WIP PR for this, see #26. I've mainly removed early returns from the `FileAssetSource.run()` method for now, and the method is already a lot more readable. I'd be interested to know if you agree with the general direction in style (for example, the heavy use of `and_then` for transactions).
