### ISSUE TITLE
Proc macro to parse UUID strings into AssetUuid at compile time

### ISSUE THREAD

**Issue by kabergstrom** [amethyst/atelier-assets#24]
It would be nice with a macro that does something like `let uuid: AssetUuid = asset_uuid!("8ce70ab5-e725-4661-bedc-bc66c2c97221")`.

**Comment by Areredify** [comment]
Is [this](https://github.com/Areredify/asset-uuid) what you need?

**Comment by kabergstrom** [comment]
Yes! This is perfect :) Thank you! Now to figure out where in the repo to put it.. Maybe we need a crate with common typedefs that is shared between all subcrates - currently AssetUuid is redundantly defined in both `importer` and `loader`. 🤔

**Comment by Areredify** [comment]
Well, you tell me, I'll do it

**Comment by kabergstrom** [comment]
I think adding a shared `atelier-core` crate with the common `utils`, typedefs for `AssetUuid`, `AssetTypeId` and similar would be great. I would accept a PR for that if you would like to write it :)

**Comment by Areredify** [comment]
Yeah, sure

**Comment by Areredify** [comment]
This can now be closed

**Comment by kabergstrom** [comment]
Thank you!
