### ISSUE TITLE
Implement hot reloading in rpc_loader

### ISSUE THREAD

**Issue by kabergstrom** [amethyst/atelier-assets#3]
Every time a new version of the metadata is created, the asset daemon's RPC server sends out a new snapshot to every registered listener (`atelier_schema::service::asset_hub::listener`). Currently, the `rpc_loader` replaces its active snapshot with the new one every time.

To implement hot reloading, the `rpc_loader` should check each new snapshot for changed assets and trigger a reload of the modified assets. I'm not sure what should happen with deleted assets, though.

**Comment by azriel91** [comment]
Implemented in #22.
