### ISSUE TITLE
update to Mozilla fork of lmdb

### ISSUE THREAD

**Issue by aclysma** [amethyst/atelier-assets#52]
It appears the original crate is no longer maintained and mozila is maintaining this fork:
https://github.com/mozilla/lmdb-rs

**Comment by erlend-sh** [comment]
There’s also this: https://github.com/Kerollmops/heed (maintained by my colleague, on behalf of MeiliSearch).

**Comment by kabergstrom** [comment]
Fixed in https://github.com/amethyst/atelier-assets/commit/e6dc8b73a1e6f20ef7305938ea6338d7cffc7612
