### ISSUE TITLE
CI tests hang on RpcIO error

### ISSUE THREAD

**Issue by ezpuzz** [amethyst/atelier-assets#78]
`Error: 1-11T00:42:06.812][ERROR][atelier_loader::rpc_io] Error connecting RpcIO: Connection refused (os error 61)`

This error is preventing tests from completing in CI.

I believe we should:

- Limit connection attempts in CI or number of retries
- Attempt to solve underlying issue.

**Comment by kabergstrom** [comment]
Could this be due to running multiple tests in parallel? The Daemon should probably start and stop properly between each test run, to ensure the port is freed

**Comment by ezpuzz** [comment]
should be fixed in #83
